export const iconMarkers={
    1: require('../assets/1-s.png'),
    2: require('../assets/2.png'),
    3: require('../assets/3-s.png'),
    4: require('../assets/4-s.png'),
    5: require('../assets/5-s.png'),
    6: require('../assets/6-s.png'),
    7: require('../assets/7-s.png'),
    8: require('../assets/8-s.png'),
    11: require('../assets/11-s.png'),
    12: require('../assets/12-s.png'),
    13: require('../assets/13-s.png'),
    14: require('../assets/14-s.png'),
    15: require('../assets/15-s.png'),
    16: require('../assets/16-s.png'),
    17: require('../assets/17-s.png'),
    18: require('../assets/18-s.png'),
    19: require('../assets/19-s.png'),
    20: require('../assets/20-s.png'),
    21: require('../assets/21-s.png'),
    22: require('../assets/22-s.png'),
    23: require('../assets/23-s.png'),
    25: require('../assets/25-s.png'),
    26: require('../assets/26-s.png'),
    29: require('../assets/29-s.png'),
    30: require('../assets/30-s.png'),
    31: require('../assets/31-s.png'),
    32: require('../assets/32-s.png'),
    33: require('../assets/33-s.png'),
    34: require('../assets/34-s.png'),
    35: require('../assets/35-s.png'),
    36: require('../assets/36-s.png'),
    37: require('../assets/37-s.png'),
    38: require('../assets/38-s.png'),
    39: require('../assets/39-s.png'),
    40: require('../assets/40-s.png'),
    41: require('../assets/41-s.png'),
    42: require('../assets/42-s.png'),
    43: require('../assets/43-s.png'),
    44: require('../assets/44-s.png'),
   
}
    